### ISSUE TITLE
events.js:160 throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by vaughanwatson** [jsguy/misojs#28]
When typing miso run the following error message comes up.
Touching system/main.js
[nodemon] 1.12.1
[nodemon] to restart at any time, enter 'rs'
[nodemon] watching: package.json ~\modules/**/* ~\system/**/* ~\cfg/**/* ~\mvc/**/* ~\client/**/* ~\server/**/* app.js
[nodemon] starting 'node --debug app.js'
events.js:160
throw er; // Unhandled 'error' event

Error: spawn cmd ENOENT
at exports._errnoException (util.js:1020:11)
at Process.ChildProcess._handle.onexit (internal/child_process.js:197:32)
at onErrorNT (internal/child_process.js:376:16)
at _combinedTickCallback (internal/process/next_tick.js:80:11)
at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by jsguy** [comment]
If you're using windows, you might be missing a path setting, try the following:

* Goto > Control Panel\System and Security\System\Advance system setting\Enviroment variables
* Set system variables path C:\Windows\System32\ variable
* Restart your System.
